@startuml

title GitLab Runner CloudFoundry Executor - Job Sequence

'skinparam monochrome true

'autonumber

participant "GitLab" as gitlab
participant "GitLab Runner - Manager" as glrm
participant "CloudFoundry PaaS" as cf
participant "GitLab Runner - Worker" as glrw
participant "Cache Storage" as cache
' Start

glrm -> gitlab : Connect and wait for job

group Run job
gitlab -> glrm : Submit new GitLab CI job

group Prepare instance
' prepare.sh
glrm -> cf : **cf push** to create new instance using defined OCI **image**
cf -> glrm : Block until instance is ready

glrm -> glrw : **cf ssh** to install prereqs and **gitlab-runner-helper**
glrw -> glrm : Return output
end

loop Run substages
' run.sh
glrm -> glrw : **cf ssh** to run job steps
glrw -> gitlab : Request code via Git
gitlab -> glrw : Return code
glrw -> cache : Request cache
cache -> glrw : Return cache

glrw -> glrw : execute job steps

glrw -> cache : Write cache

glrw -> glrm : Return job output
end

group Cleanup instance
glrm -> cf : **cf delete** to remove instance
end

group Return results
glrm -> gitlab : Return job results
end

end
@enduml
