# Configuration for the custom CloudFoundry executor
[[runners]]
  executor = "custom"
  builds_dir = "/tmp/build"
  cache_dir = "/tmp/cache"
  [runners.custom]
    #config_exec = "/home/vcap/app/cf-driver/config.sh"
    prepare_exec = "/home/vcap/app/cf-driver/prepare.sh"
    run_exec = "/home/vcap/app/cf-driver/run.sh"
    cleanup_exec = "/home/vcap/app/cf-driver/cleanup.sh"
