# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: "CF Driver: Go Build & Test"

on: [pull_request]

defaults:
  run:
    working-directory: runner/cfd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: runner/cfd/go.mod
          cache-dependency-path: runner/cfd/go.sum

      - name: Install dependencies
        run: go get .

      - name: Check formatting
        run: test -z "$(gofmt -l .)"

      - name: Vet
        run: go vet ./...

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
