name: Terraform Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration test
    steps:
      - uses: actions/checkout@v4

      - name: terraform validate
        uses: dflook/terraform-validate@a8236b6ed2ac088b60f65142d4933e6bfc9d71ec #v1.47.0

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@84e7351536952f1ba88f750a17e5bcfcf55dbd0e #v1.47.0

      - name: terraform test
        uses: dflook/terraform-test@f203156ff9dbd7e7ae26e7dc2f7c8530262a88ff #v1.47.0
        env:
          CF_API_URL: "https://api.fr.cloud.gov"
          CF_USER: ${{ secrets.CF_USER }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          TERRAFORM_PRE_RUN: |
            apt-get update
            apt-get install -y zip
        with:
          variables: |
            cf_org_managers: ["${{ secrets.CF_USER }}"]


  validate-sandbox:
    runs-on: ubuntu-latest
    name: Validate sandbox
    steps:
      - uses: actions/checkout@v4

      - name: terraform validate
        uses: dflook/terraform-validate@a8236b6ed2ac088b60f65142d4933e6bfc9d71ec #v1.47.0
        with:
          path: sandbox-deploy
