name: Terraform Test

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Integration test
    steps:
      - uses: actions/checkout@v4

      - name: terraform validate
        uses: dflook/terraform-validate@v1

      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1

      - name: terraform test
        uses: dflook/terraform-test@v1
        env:
          CF_USER: ${{ secrets.CF_USER }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
          TF_VAR_cf_org_manager: ${{ secrets.CF_USER }}
          TF_VAR_cf_community_user: ${{ secrets.CF_USER }}
          TERRAFORM_PRE_RUN: |
            apt-get update
            apt-get install -y zip


  validate-sandbox:
    runs-on: ubuntu-latest
    name: Validate sandbox
    steps:
      - uses: actions/checkout@v4

      - name: terraform validate
        uses: dflook/terraform-validate@v1
        with:
          path: sandbox-deploy
